### ISSUE TITLE
User Story: List of Products

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#10]
As a **user/costumer**  I can **view products in a list format** so that **I can easily compare them.**

### Acceptance Criteria:
- Products are displayed in a clear and organised manner.
- Product list includes product image, name, price, and brief description.
- Product list includes sorting and filtering options.

### Tasks:
- [x] Implement display of products in a list format.
- [x] Include product image, name, price, and ratings in product list.
- [x] Implement sorting and filtering options for the product list.

#8
