### ISSUE TITLE
User Story: Product Details

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#11]
As a **user/costumer**  I can **view the product details** so that **I can make an informed decision about my purchase.**

### Acceptance Criteria:
- Product detail page includes product images, name, price, description, and product options (if applicable).
- Product detail page includes customer reviews and ratings.
- Product detail page includes a "Add to Cart" button.

### Tasks:
- [x] Design and implement the product detail page.
- [x] Include product images, name, price, description, and product options (if applicable).
- [x] Implement display of customer reviews and ratings.
- [x] Include an "Add to Cart" button on the product detail page.

#8
