### ISSUE TITLE
User Story: Approve Reviews

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#13]
As a **store owner** I can **approve reviews from costumers** so that **they will be shown on the product page**.

### Acceptance Criteria:
- Reviews are moderated by the site admin before being published.
- Reviews can be seen by other customers on the product detail page.

### Tasks:
- [x] Implement a view to handle review submissions.
- [x] Create a moderation queue for reviews awaiting approval.
- [x] Implement a view for the site admin to approve or reject reviews.
- [x] Display approved reviews on the product detail page.

#8
