### ISSUE TITLE
User Story: Delete Product

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#22]
As a **store owner**  I can **delete a product from the store** so that **it is no longer available for purchase.**

### Acceptance Criteria:
- The admin dashboard includes an option to delete a product.
- When a product is deleted, it no longer appears on the public-facing website.

### Tasks:
- [x] Design and implement the delete product functionality.
- [x] Implement a confirmation message to ensure that the admin wants to delete the product.
- [x] Implement functionality to remove the product from the database.
- [x] Implement functionality to remove the product from the public-facing website.

#14
