### ISSUE TITLE
User Story: Sort Products

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#26]
As a **user/costumer**  I can **sort products by different criteria** so that **I can easily find the products that best fit my needs.**

### Acceptance Criteria:
- The website allows for sorting by various criteria, such as price, category, and rating.
- The sorting function works quickly and accurately.
- The sorting function can be easily accessed by the user.

### Tasks:
- [x] Design and implement the sorting feature on the website.
- [x] Implement functionality to sort the database query results by the selected criteria.
- [x] Implement functionality to display the sorted results to the user.

#17
