### ISSUE TITLE
User Story: Adding Products to Bag and Adjusting Quantity

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#29]
As a **user/costumer**  I can **add a product to my bag, adjust the quantity of the product, select the colour of the product and view my bag before proceeding to checkout** so that **I can make sure that the products and quantities I want are correct before completing my purchase.**

### Acceptance Criteria:
- Costumers can select a product size and quantity and add it to their bag.
- Costumers can adjust the quantity of products in their bag before checkout.
- Costumers can view their bag and the products they have added to it.

### Tasks:
- [x] Add a "Add to Bag" button to the product detail page.
- [x] Allow costumer to select the quantity of the product and the colour of the product (if applicable).
- [x] Add the product to the bag and display a notification indicating that the product has been added to the bag.
- [x] Add a "View bag " button to the notification and the product detail page.
- [x] Allow shoppers to adjust the quantity of products in their bag.

#28
