### ISSUE TITLE
User Story: Add Favourites

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#33]
As a **user/costumer**  I can **add a product to my list of favourite products** so that **I can easily find it later.**

### Acceptance Criteria:
- When I am logged in as a costumer I should see an "Add to Favourites" button on the product detail page.
- When I click the "Add to Favourites" button, the product should be added to my list of favourite products.
- If I am not logged in, I should be prompted to log in or create an account before I can add a product to my list of favourite products.

### Tasks:
- [x] Create a new model to store favourite products for each user.
- [x] Add a button to the product detail page template that allows the user to add the product to their list of favourite products.
- [x] Add a view function that handles the request to add a product to the user's list of favourite products.
- [x] Add a check to ensure that only logged-in users can add products to their list of favourite products.

#32
