### ISSUE TITLE
User Story: View Favourites

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#34]
As a **user/costumer**  I can **view my list of favourite products** so that **I can see what I have saved.**

### Acceptance Criteria:
- When I am logged in as a costumer, I should see a "Favourites" link in the main navigation menu.
- When I click the "Favourites" link, I should be taken to a page that displays all the products I have saved as favourites.
- If I have not saved any favourite products yet, I should see a message indicating that my list is empty.

### Tasks:
- [x] Add a link to the main navigation menu that takes the user to their list of favourite products.
- [x] Create a new view function that handles the request to display the user's list of favourite products.
- [x] Create a template that displays the user's list of favourite products, including the product name, image, and price.
- [x] Add a check to ensure that only logged-in users can view their list of favourite products.

#32
