### ISSUE TITLE
User Story: Remove Favourites

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#35]
As a **user/costumer**  I can **remove a product from my list of favourite products** so that **I can keep my list up to date.**

### Acceptance Criteria:
- When I am logged in as a costumer and viewing my list of favourite products, I should see a "Remove" button next to each product.
- When I click the "Remove" button next to a product, that product should be removed from my list of favourite products.

### Tasks:
- [x] Add a "Remove" button to the template that displays the user's list of favourite products.
- [x] Create a new view function that handles the request to remove a product from the user's list of favourite products.
- [x] Add a check to ensure that only logged-in users can remove products from their list of favourite products.
- [x] Update the model and database to remove the product from the user's list of favourite products.

#32
