### ISSUE TITLE
User Story: User Account Management

### ISSUE THREAD

**Issue by CarmenCantudo** [CarmenCantudo/my-first-box#7]
As a **website owner** I can **view a list of registered users and their information** so that **I can manage user's accounts**.

### Acceptance Criteria:
- The website must include a user management section.
- The user management section must include a listing of all registered users and their information.
- The user management section must include functionality to view and edit user information.

### Tasks:
- [ ] Create a user management section in the content management system.
- [ ] Implement functionality to display a listing of all registered users and their information.
- [ ] Add functionality to view and edit user information in the user management section.

#2
